// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTaskInput struct {
	Title string `json:"title"`
}

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}

type UpdateTaskInput struct {
	Title     *string `json:"title,omitempty"`
	Completed *bool   `json:"completed,omitempty"`
}
